[package]
name = "robloxiandemo/string"
description = "A vast collection of very useful string-related functions, which has built-in compatiblity for usage with Wally."
version = "0.1.2"
license = "MIT"
authors = ["Demo (https://github.com/RobloxianDemo)"]
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"